-- =====================================================================
--  FilmBox — jeu de données du projet fil rouge (séance 1)
--  Films et castings réels ; membres, notes et visionnages fictifs.
--  Script ré-exécutable : il supprime puis recrée toutes les tables.
--  À charger dans une base dédiée :  CREATE DATABASE filmbox;
-- =====================================================================

-- (listes et liste_films sont créées pendant la mission M1)
DROP TABLE IF EXISTS liste_films, listes, journal, notes, casting, films, sagas, personnes, utilisateurs CASCADE;

CREATE TABLE sagas (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE films (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre              VARCHAR(120) NOT NULL,
    annee              INTEGER      NOT NULL CHECK (annee BETWEEN 1888 AND 2100),
    genre              VARCHAR(30)  NOT NULL,
    saga_id            INTEGER REFERENCES sagas(id),
    film_precedent_id  INTEGER REFERENCES films(id)     -- épisode précédent dans la saga
);

CREATE TABLE personnes (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE casting (
    film_id     INTEGER NOT NULL REFERENCES films(id),
    personne_id INTEGER NOT NULL REFERENCES personnes(id),
    role        VARCHAR(12) NOT NULL CHECK (role IN ('acteur', 'realisateur')),
    PRIMARY KEY (film_id, personne_id, role)
);

CREATE TABLE utilisateurs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo      VARCHAR(30) NOT NULL UNIQUE,
    ville       VARCHAR(50),
    inscrit_le  DATE NOT NULL
);

CREATE TABLE notes (
    utilisateur_id INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id        INTEGER NOT NULL REFERENCES films(id),
    note           NUMERIC(2,1) NOT NULL CHECK (note BETWEEN 0.5 AND 5),
    note_le        DATE NOT NULL,
    PRIMARY KEY (utilisateur_id, film_id)                -- une note par membre et par film
);

CREATE TABLE journal (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id         INTEGER NOT NULL REFERENCES films(id),
    date_visionnage DATE    NOT NULL
);

-- ---------- Sagas ----------
INSERT INTO sagas (nom) VALUES ('Retour vers le futur'), ('The Dark Knight'), ('X-Men : la prélogie');

-- ---------- Films ----------
INSERT INTO films (titre, annee, genre, saga_id) VALUES
 ('Apollo 13', 1995, 'Drame', NULL),                                  -- 1
 ('Mystic River', 2003, 'Thriller', NULL),                            -- 2
 ('Des hommes d''honneur', 1992, 'Drame', NULL),                      -- 3
 ('X-Men : Le Commencement', 2011, 'Science-fiction', 3),             -- 4
 ('X-Men : Days of Future Past', 2014, 'Science-fiction', 3),         -- 5
 ('X-Men : Apocalypse', 2016, 'Science-fiction', 3),                  -- 6
 ('Forrest Gump', 1994, 'Drame', NULL),                               -- 7
 ('Seul au monde', 2000, 'Aventure', NULL),                           -- 8
 ('Il faut sauver le soldat Ryan', 1998, 'Guerre', NULL),             -- 9
 ('Arrête-moi si tu peux', 2002, 'Policier', NULL),                   -- 10
 ('Titanic', 1997, 'Romance', NULL),                                  -- 11
 ('Inception', 2010, 'Science-fiction', NULL),                        -- 12
 ('Les Infiltrés', 2006, 'Policier', NULL),                           -- 13
 ('Once Upon a Time… in Hollywood', 2019, 'Comédie', NULL),           -- 14
 ('Le Loup de Wall Street', 2013, 'Comédie', NULL),                   -- 15
 ('Fight Club', 1999, 'Thriller', NULL),                              -- 16
 ('Ocean''s Eleven', 2001, 'Policier', NULL),                         -- 17
 ('Seven', 1995, 'Thriller', NULL),                                   -- 18
 ('Batman Begins', 2005, 'Action', 2),                                -- 19
 ('The Dark Knight', 2008, 'Action', 2),                              -- 20
 ('The Dark Knight Rises', 2012, 'Action', 2),                        -- 21
 ('Les Évadés', 1994, 'Drame', NULL),                                 -- 22
 ('Intouchables', 2011, 'Comédie', NULL),                             -- 23
 ('La Môme', 2007, 'Drame', NULL),                                    -- 24
 ('The Artist', 2011, 'Comédie', NULL),                               -- 25
 ('Le Fabuleux Destin d''Amélie Poulain', 2001, 'Comédie', NULL),     -- 26
 ('La Haine', 1995, 'Drame', NULL),                                   -- 27
 ('Retour vers le futur', 1985, 'Science-fiction', 1),                -- 28
 ('Retour vers le futur II', 1989, 'Science-fiction', 1),             -- 29
 ('Retour vers le futur III', 1990, 'Science-fiction', 1);            -- 30

-- Chaînage des sagas : chaque épisode pointe vers le précédent
UPDATE films SET film_precedent_id = 4  WHERE id = 5;
UPDATE films SET film_precedent_id = 5  WHERE id = 6;
UPDATE films SET film_precedent_id = 19 WHERE id = 20;
UPDATE films SET film_precedent_id = 20 WHERE id = 21;
UPDATE films SET film_precedent_id = 28 WHERE id = 29;
UPDATE films SET film_precedent_id = 29 WHERE id = 30;

-- ---------- Personnes et casting ----------
-- Table de travail temporaire : (film, personne, rôle) en toutes lettres
CREATE TEMP TABLE _casting (film_id INTEGER, nom VARCHAR(80), role VARCHAR(12));
INSERT INTO _casting VALUES
 (1,'Tom Hanks','acteur'),(1,'Kevin Bacon','acteur'),(1,'Bill Paxton','acteur'),(1,'Gary Sinise','acteur'),(1,'Ed Harris','acteur'),(1,'Ron Howard','realisateur'),
 (2,'Sean Penn','acteur'),(2,'Tim Robbins','acteur'),(2,'Kevin Bacon','acteur'),(2,'Laurence Fishburne','acteur'),(2,'Clint Eastwood','realisateur'),
 (3,'Tom Cruise','acteur'),(3,'Jack Nicholson','acteur'),(3,'Demi Moore','acteur'),(3,'Kevin Bacon','acteur'),(3,'Rob Reiner','realisateur'),
 (4,'James McAvoy','acteur'),(4,'Michael Fassbender','acteur'),(4,'Jennifer Lawrence','acteur'),(4,'Kevin Bacon','acteur'),(4,'Matthew Vaughn','realisateur'),
 (5,'Hugh Jackman','acteur'),(5,'James McAvoy','acteur'),(5,'Michael Fassbender','acteur'),(5,'Jennifer Lawrence','acteur'),(5,'Omar Sy','acteur'),(5,'Bryan Singer','realisateur'),
 (6,'James McAvoy','acteur'),(6,'Michael Fassbender','acteur'),(6,'Jennifer Lawrence','acteur'),(6,'Bryan Singer','realisateur'),
 (7,'Tom Hanks','acteur'),(7,'Robin Wright','acteur'),(7,'Gary Sinise','acteur'),(7,'Robert Zemeckis','realisateur'),
 (8,'Tom Hanks','acteur'),(8,'Helen Hunt','acteur'),(8,'Robert Zemeckis','realisateur'),
 (9,'Tom Hanks','acteur'),(9,'Matt Damon','acteur'),(9,'Tom Sizemore','acteur'),(9,'Vin Diesel','acteur'),(9,'Steven Spielberg','realisateur'),
 (10,'Leonardo DiCaprio','acteur'),(10,'Tom Hanks','acteur'),(10,'Steven Spielberg','realisateur'),
 (11,'Leonardo DiCaprio','acteur'),(11,'Kate Winslet','acteur'),(11,'James Cameron','realisateur'),
 (12,'Leonardo DiCaprio','acteur'),(12,'Joseph Gordon-Levitt','acteur'),(12,'Elliot Page','acteur'),(12,'Tom Hardy','acteur'),(12,'Marion Cotillard','acteur'),(12,'Michael Caine','acteur'),(12,'Christopher Nolan','realisateur'),
 (13,'Leonardo DiCaprio','acteur'),(13,'Matt Damon','acteur'),(13,'Jack Nicholson','acteur'),(13,'Martin Scorsese','realisateur'),
 (14,'Leonardo DiCaprio','acteur'),(14,'Brad Pitt','acteur'),(14,'Margot Robbie','acteur'),(14,'Quentin Tarantino','realisateur'),
 (15,'Leonardo DiCaprio','acteur'),(15,'Jonah Hill','acteur'),(15,'Margot Robbie','acteur'),(15,'Jean Dujardin','acteur'),(15,'Martin Scorsese','realisateur'),
 (16,'Brad Pitt','acteur'),(16,'Edward Norton','acteur'),(16,'Helena Bonham Carter','acteur'),(16,'David Fincher','realisateur'),
 (17,'George Clooney','acteur'),(17,'Brad Pitt','acteur'),(17,'Matt Damon','acteur'),(17,'Julia Roberts','acteur'),(17,'Steven Soderbergh','realisateur'),
 (18,'Brad Pitt','acteur'),(18,'Morgan Freeman','acteur'),(18,'David Fincher','realisateur'),
 (19,'Christian Bale','acteur'),(19,'Michael Caine','acteur'),(19,'Liam Neeson','acteur'),(19,'Morgan Freeman','acteur'),(19,'Gary Oldman','acteur'),(19,'Christopher Nolan','realisateur'),
 (20,'Christian Bale','acteur'),(20,'Heath Ledger','acteur'),(20,'Michael Caine','acteur'),(20,'Morgan Freeman','acteur'),(20,'Gary Oldman','acteur'),(20,'Christopher Nolan','realisateur'),
 (21,'Christian Bale','acteur'),(21,'Tom Hardy','acteur'),(21,'Anne Hathaway','acteur'),(21,'Joseph Gordon-Levitt','acteur'),(21,'Marion Cotillard','acteur'),(21,'Michael Caine','acteur'),(21,'Gary Oldman','acteur'),(21,'Morgan Freeman','acteur'),(21,'Christopher Nolan','realisateur'),
 (22,'Tim Robbins','acteur'),(22,'Morgan Freeman','acteur'),(22,'Frank Darabont','realisateur'),
 (23,'François Cluzet','acteur'),(23,'Omar Sy','acteur'),(23,'Olivier Nakache','realisateur'),(23,'Éric Toledano','realisateur'),
 (24,'Marion Cotillard','acteur'),(24,'Gérard Depardieu','acteur'),(24,'Olivier Dahan','realisateur'),
 (25,'Jean Dujardin','acteur'),(25,'Bérénice Bejo','acteur'),(25,'Michel Hazanavicius','realisateur'),
 (26,'Audrey Tautou','acteur'),(26,'Mathieu Kassovitz','acteur'),(26,'Jean-Pierre Jeunet','realisateur'),
 (27,'Vincent Cassel','acteur'),(27,'Hubert Koundé','acteur'),(27,'Saïd Taghmaoui','acteur'),(27,'Mathieu Kassovitz','realisateur'),
 (28,'Michael J. Fox','acteur'),(28,'Christopher Lloyd','acteur'),(28,'Lea Thompson','acteur'),(28,'Robert Zemeckis','realisateur'),
 (29,'Michael J. Fox','acteur'),(29,'Christopher Lloyd','acteur'),(29,'Lea Thompson','acteur'),(29,'Robert Zemeckis','realisateur'),
 (30,'Michael J. Fox','acteur'),(30,'Christopher Lloyd','acteur'),(30,'Lea Thompson','acteur'),(30,'Robert Zemeckis','realisateur');

INSERT INTO personnes (nom) SELECT DISTINCT nom FROM _casting ORDER BY nom;
INSERT INTO casting (film_id, personne_id, role)
SELECT c.film_id, p.id, c.role FROM _casting c JOIN personnes p ON p.nom = c.nom;

-- ---------- Membres (fictifs) ----------
INSERT INTO utilisateurs (pseudo, ville, inscrit_le) VALUES
 ('cinephile_92', 'Nanterre',  '2024-03-12'),
 ('popcorn_queen','Lyon',      '2024-09-01'),
 ('nolanfan',     'Paris',     '2025-01-05'),
 ('maxou_ciné',   'Marseille', '2025-02-20'),
 ('lea.reel',     'Lille',     '2025-04-02'),
 ('darkroom',     'Nantes',    '2025-06-18'),
 ('bobine',       'Bordeaux',  '2025-09-07'),
 ('sofa_critic',  'Paris',     '2025-12-11');

-- ---------- Notes et visionnages (générés, mais déterministes) ----------
-- Chaque film a une « qualité » de base ; chaque membre note autour de cette base.
CREATE TEMP TABLE _base (film_id INTEGER, base NUMERIC);
INSERT INTO _base VALUES
 (1,3.8),(2,4.0),(3,3.6),(4,3.7),(5,3.9),(6,3.0),(7,4.4),(8,3.7),(9,4.3),(10,4.0),
 (11,3.9),(12,4.4),(13,4.2),(14,3.8),(15,4.1),(16,4.4),(17,3.6),(18,4.3),(19,3.9),(20,4.7),
 (21,3.9),(22,4.8),(23,4.3),(24,3.7),(25,3.8),(26,4.2),(27,4.3),(28,4.5),(29,3.9),(30,3.5);

CREATE TEMP TABLE _h AS
SELECT u.id AS utilisateur_id, b.film_id, b.base,
       ('x' || substr(md5(u.id || '-' || b.film_id), 1, 8))::bit(32)::int AS h
FROM utilisateurs u CROSS JOIN _base b;

-- Environ 2 films sur 3 vus par chaque membre
INSERT INTO notes (utilisateur_id, film_id, note, note_le)
SELECT utilisateur_id, film_id,
       LEAST(5, GREATEST(0.5, ROUND((base + ((abs(h) % 11) - 5) * 0.15) * 2) / 2)),
       DATE '2026-01-05' + (abs(h / 7) % 255)
FROM _h
WHERE abs(h) % 3 <> 0;

-- Un visionnage par note, à la date de la note
INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT utilisateur_id, film_id, note_le FROM notes;

-- Quelques revisionnages
INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT n.utilisateur_id, n.film_id, n.note_le + 30 + (n.film_id % 20)
FROM notes n
WHERE n.note >= 4.5 AND n.note_le + 30 + (n.film_id % 20) <= DATE '2026-09-20';

DROP TABLE _casting, _base, _h;

-- ---------- Contrôle ----------
SELECT 'films' AS table_name, COUNT(*) AS lignes FROM films
UNION ALL SELECT 'personnes', COUNT(*) FROM personnes
UNION ALL SELECT 'casting', COUNT(*) FROM casting
UNION ALL SELECT 'utilisateurs', COUNT(*) FROM utilisateurs
UNION ALL SELECT 'notes', COUNT(*) FROM notes
UNION ALL SELECT 'journal', COUNT(*) FROM journal;


--------------------

-- M1.2 — La table listes

CREATE  TABLE  listes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id      INTEGER         NOT NULL  REFERENCES utilisateurs(id),
    titre               VARCHAR(100)    NOT NULL,
    visibilite          VARCHAR(100)    NOT NULL DEFAULT 'privee'   CHECK ( visibilite IN ('publique', 'privee')),
    date                DATE            NOT NULL DEFAULT CURRENT_DATE
);

-- M1.3 — La table liste_films

CREATE TABLE liste_films (
    liste_id  INTEGER NOT NULL REFERENCES listes(id) ON DELETE CASCADE,
    film_id   INTEGER NOT NULL REFERENCES films(id),
    position  INTEGER NOT NULL CHECK (position > 0),
    PRIMARY KEY (liste_id, film_id)
);

-- M1.4 Le top Nolan

INSERT INTO listes (utilisateur_id, titre, visibilite) SELECT id, 'Mon top Nolan', 'publique' FROM utilisateurs WHERE pseudo = 'nolanfan';
INSERT INTO liste_films (liste_id, film_id, position) SELECT listes.id, films.id, top_nolan.position FROM listes
CROSS JOIN (VALUES
    ('The Dark Knight', 1),
    ('Inception',       2),
    ('Batman Begins',   3)
) AS top_nolan (titre, position)
JOIN films ON films.titre = top_nolan.titre WHERE listes.titre = 'Mon top Nolan';

SELECT listes.titre AS liste, liste_films.position, films.titre AS film
FROM listes
JOIN liste_films ON liste_films.liste_id = listes.id
JOIN films ON films.id = liste_films.film_id
WHERE listes.titre = 'Mon top Nolan' ORDER BY liste_films.position;

-- M2.1 Les années 2000

SELECT titre, annee, genre FROM films WHERE annee BETWEEN 2000 AND 2010 ORDER BY annee, titre;

-- M2.2 La filmographie de Kevin Bacon

SELECT films.titre, films.annee FROM films
JOIN casting ON casting.film_id = films.id
JOIN personnes ON personnes.id = casting.personne_id
WHERE personnes.nom = 'Kevin Bacon' AND casting.role = 'acteur' ORDER BY films.annee;

-- M2.3 Les réalisateurs prolifiques

SELECT personnes.nom AS realisateur, COUNT(*) AS nb_films FROM personnes
JOIN casting ON casting.personne_id = personnes.id
WHERE casting.role = 'realisateur'
GROUP BY personnes.id, personnes.nom
HAVING COUNT(*) >= 2
ORDER BY nb_films DESC, realisateur;

-- M2.4 Les mieux notés

SELECT films.titre, ROUND(AVG(notes.note), 2) AS moyenne, COUNT(*) AS nb_notes FROM films
JOIN notes ON notes.film_id = films.id
GROUP BY films.id, films.titre
HAVING COUNT(*) >= 5
ORDER BY moyenne DESC, films.titre
LIMIT 5;

-- M2.5 Les membres les plus actifs

SELECT utilisateurs.pseudo,
       COUNT(journal.id) AS nb_visionnages,
       COUNT(DISTINCT journal.film_id) AS nb_films_distincts
FROM utilisateurs
LEFT JOIN journal ON journal.utilisateur_id = utilisateurs.id
GROUP BY utilisateurs.id, utilisateurs.pseudo
ORDER BY nb_visionnages DESC, utilisateurs.pseudo;

-- M3.1 La carte de profil

WITH membre AS (
    SELECT id, pseudo FROM utilisateurs WHERE pseudo = 'cinephile_92'
),
nombre_notes AS (
    SELECT COUNT(*) AS nb_films_notes FROM notes
    WHERE utilisateur_id = (SELECT id FROM membre)
),
moyenne_notes AS (
    SELECT ROUND(AVG(note), 2) AS note_moyenne FROM notes
    WHERE utilisateur_id = (SELECT id FROM membre)
),
genre_favori AS (
    SELECT films.genre AS genre_prefere FROM notes
    JOIN films ON films.id = notes.film_id
    WHERE notes.utilisateur_id = (SELECT id FROM membre)
    GROUP BY films.genre
    ORDER BY COUNT(*) DESC, films.genre
    LIMIT 1
),
film_favori AS (
    SELECT films.titre AS coup_de_coeur FROM notes
    JOIN films ON films.id = notes.film_id
    WHERE notes.utilisateur_id = (SELECT id FROM membre)
    ORDER BY notes.note DESC, notes.note_le
    LIMIT 1
)
SELECT membre.pseudo, nombre_notes.nb_films_notes, moyenne_notes.note_moyenne,
       genre_favori.genre_prefere, film_favori.coup_de_coeur
FROM membre
CROSS JOIN nombre_notes
CROSS JOIN moyenne_notes
CROSS JOIN genre_favori
CROSS JOIN film_favori;

-- M3.2 À voir ensuite

SELECT films.titre, films.annee FROM films
WHERE NOT EXISTS (
    SELECT 1 FROM journal
    JOIN utilisateurs ON utilisateurs.id = journal.utilisateur_id
    WHERE journal.film_id = films.id AND utilisateurs.pseudo = 'cinephile_92'
)
ORDER BY films.annee DESC, films.titre;

-- M3.3 Les films qui divisent

SELECT films.titre,
       MIN(notes.note) AS pire,
       MAX(notes.note) AS meilleure,
       MAX(notes.note) - MIN(notes.note) AS ecart
FROM films
JOIN notes ON notes.film_id = films.id
GROUP BY films.id, films.titre
ORDER BY ecart DESC, films.titre
LIMIT 5;

-- M4.1 Dans l'ordre, s'il vous plaît

WITH RECURSIVE episodes AS (
    SELECT films.id, films.titre, films.annee, 1 AS episode FROM films
    JOIN sagas ON sagas.id = films.saga_id
    WHERE sagas.nom = 'Retour vers le futur' AND films.film_precedent_id IS NULL
    UNION ALL
    SELECT films.id, films.titre, films.annee, episodes.episode + 1 FROM films
    JOIN episodes ON films.film_precedent_id = episodes.id
)
SELECT episode, titre, annee FROM episodes ORDER BY episode;

-- M4.2 Toutes les sagas

WITH RECURSIVE episodes AS (
    SELECT films.id, films.saga_id, 1 AS episode, films.titre::TEXT AS parcours FROM films
    WHERE films.saga_id IS NOT NULL AND films.film_precedent_id IS NULL
    UNION ALL
    SELECT films.id, films.saga_id, episodes.episode + 1, episodes.parcours || ' → ' || films.titre FROM films
    JOIN episodes ON films.film_precedent_id = episodes.id
)
SELECT sagas.nom AS saga, episodes.episode, episodes.parcours FROM episodes
JOIN sagas ON sagas.id = episodes.saga_id
ORDER BY saga, episodes.episode;

-- M4.3 Le nombre de Kevin Bacon

WITH RECURSIVE partenaires AS (
    SELECT DISTINCT casting_acteur.personne_id AS acteur_id, casting_partenaire.personne_id AS partenaire_id
    FROM casting AS casting_acteur
    JOIN casting AS casting_partenaire ON casting_partenaire.film_id = casting_acteur.film_id
    WHERE casting_acteur.role = 'acteur'
      AND casting_partenaire.role = 'acteur'
      AND casting_partenaire.personne_id <> casting_acteur.personne_id
),
distances AS (
    SELECT id AS acteur_id, 0 AS degre FROM personnes WHERE nom = 'Kevin Bacon'
    UNION ALL
    SELECT partenaires.partenaire_id, distances.degre + 1 FROM distances
    JOIN partenaires ON partenaires.acteur_id = distances.acteur_id
    WHERE distances.degre < 4
)
SELECT personnes.nom, MIN(distances.degre) AS nombre_de_bacon FROM distances
JOIN personnes ON personnes.id = distances.acteur_id
GROUP BY personnes.id, personnes.nom
ORDER BY nombre_de_bacon DESC, personnes.nom
LIMIT 8;

-- M4.4 D'Omar Sy à Kevin Bacon

WITH RECURSIVE chemins AS (
    SELECT id AS acteur_id, 0 AS degre, nom::TEXT AS chemin, ARRAY[id] AS visites FROM personnes
    WHERE nom = 'Kevin Bacon'
    UNION ALL
    SELECT partenaire.id,
           chemins.degre + 1,
           chemins.chemin || ' — ' || films.titre || ' — ' || partenaire.nom,
           chemins.visites || partenaire.id
    FROM chemins
    JOIN casting AS casting_acteur ON casting_acteur.personne_id = chemins.acteur_id AND casting_acteur.role = 'acteur'
    JOIN casting AS casting_partenaire ON casting_partenaire.film_id = casting_acteur.film_id AND casting_partenaire.role = 'acteur'
    JOIN films ON films.id = casting_acteur.film_id
    JOIN personnes AS partenaire ON partenaire.id = casting_partenaire.personne_id
    WHERE partenaire.id <> ALL (chemins.visites)
      AND chemins.degre < 4
)
SELECT chemins.degre, chemins.chemin FROM chemins
JOIN personnes ON personnes.id = chemins.acteur_id
WHERE personnes.nom = 'Omar Sy'
ORDER BY chemins.degre, chemins.chemin
LIMIT 1;

-- M4.5 Les inaccessibles

WITH RECURSIVE partenaires AS (
    SELECT DISTINCT casting_acteur.personne_id AS acteur_id, casting_partenaire.personne_id AS partenaire_id
    FROM casting AS casting_acteur
    JOIN casting AS casting_partenaire ON casting_partenaire.film_id = casting_acteur.film_id
    WHERE casting_acteur.role = 'acteur'
      AND casting_partenaire.role = 'acteur'
      AND casting_partenaire.personne_id <> casting_acteur.personne_id
),
accessibles AS (
    SELECT id AS acteur_id FROM personnes WHERE nom = 'Kevin Bacon'
    UNION
    SELECT partenaires.partenaire_id FROM accessibles
    JOIN partenaires ON partenaires.acteur_id = accessibles.acteur_id
)
SELECT personnes.nom FROM personnes
WHERE EXISTS (SELECT 1 FROM casting WHERE casting.personne_id = personnes.id AND casting.role = 'acteur')
  AND NOT EXISTS (SELECT 1 FROM accessibles WHERE accessibles.acteur_id = personnes.id)
ORDER BY personnes.nom;

-- M5.1 Top 3 par genre

WITH moyennes AS (
    SELECT films.genre, films.titre, ROUND(AVG(notes.note), 2) AS moyenne FROM films
    JOIN notes ON notes.film_id = films.id
    GROUP BY films.id, films.genre, films.titre
    HAVING COUNT(*) >= 3
),
classement AS (
    SELECT genre, titre, moyenne,
           ROW_NUMBER() OVER (PARTITION BY genre ORDER BY moyenne DESC, titre) AS rang
    FROM moyennes
)
SELECT genre, rang, titre, moyenne FROM classement
WHERE rang <= 3
ORDER BY genre, rang;

-- M5.2 Le classement des réalisateurs

WITH moyennes AS (
    SELECT personnes.nom AS realisateur, ROUND(AVG(notes.note), 2) AS moyenne, COUNT(*) AS nb_notes FROM personnes
    JOIN casting ON casting.personne_id = personnes.id AND casting.role = 'realisateur'
    JOIN notes ON notes.film_id = casting.film_id
    GROUP BY personnes.id, personnes.nom
),
classement AS (
    SELECT DENSE_RANK() OVER (ORDER BY moyenne DESC) AS rang, realisateur, moyenne, nb_notes
    FROM moyennes
)
SELECT rang, realisateur, moyenne, nb_notes FROM classement
WHERE rang <= 10
ORDER BY rang, realisateur;

-- M5.3 Le coup de cœur de chacun

WITH classement AS (
    SELECT utilisateurs.pseudo, films.titre, notes.note, notes.note_le,
           ROW_NUMBER() OVER (PARTITION BY notes.utilisateur_id ORDER BY notes.note DESC, notes.note_le) AS rang
    FROM notes
    JOIN utilisateurs ON utilisateurs.id = notes.utilisateur_id
    JOIN films ON films.id = notes.film_id
)
SELECT pseudo, titre, note, note_le FROM classement
WHERE rang = 1
ORDER BY pseudo;

-- M5.4 Le meilleur épisode

WITH moyennes AS (
    SELECT sagas.nom AS saga, films.titre, ROUND(AVG(notes.note), 2) AS moyenne FROM films
    JOIN sagas ON sagas.id = films.saga_id
    JOIN notes ON notes.film_id = films.id
    GROUP BY sagas.nom, films.id, films.titre
)
SELECT saga, titre, moyenne,
       RANK() OVER (PARTITION BY saga ORDER BY moyenne DESC) AS rang_dans_saga
FROM moyennes
ORDER BY saga, rang_dans_saga, titre;

-- M6.1 Visionnages cumulés

WITH par_mois AS (
    SELECT TO_CHAR(journal.date_visionnage, 'YYYY-MM') AS mois, COUNT(*) AS nb FROM journal
    JOIN utilisateurs ON utilisateurs.id = journal.utilisateur_id
    WHERE utilisateurs.pseudo = 'cinephile_92'
    GROUP BY mois
)
SELECT mois, nb, SUM(nb) OVER (ORDER BY mois) AS cumul FROM par_mois
ORDER BY mois;

-- M6.2 La note d'Inception au fil du temps

SELECT notes.note_le, utilisateurs.pseudo, notes.note,
       ROUND(AVG(notes.note) OVER (ORDER BY notes.note_le ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS moyenne_cumulee
FROM notes
JOIN films ON films.id = notes.film_id
JOIN utilisateurs ON utilisateurs.id = notes.utilisateur_id
WHERE films.titre = 'Inception'
ORDER BY notes.note_le;

-- M6.3 Plus sévère que la moyenne ?

WITH notes_avec_moyenne AS (
    SELECT utilisateur_id, film_id, note,
           ROUND(AVG(note) OVER (PARTITION BY film_id), 2) AS moyenne_film
    FROM notes
)
SELECT utilisateurs.pseudo, films.titre, notes_avec_moyenne.note, notes_avec_moyenne.moyenne_film,
       notes_avec_moyenne.note - notes_avec_moyenne.moyenne_film AS ecart
FROM notes_avec_moyenne
JOIN utilisateurs ON utilisateurs.id = notes_avec_moyenne.utilisateur_id
JOIN films ON films.id = notes_avec_moyenne.film_id
WHERE utilisateurs.pseudo = 'nolanfan'
ORDER BY ecart DESC, films.titre;

-- M6.4 Le rythme de visionnage

SELECT journal.date_visionnage, films.titre,
       journal.date_visionnage - LAG(journal.date_visionnage) OVER (ORDER BY journal.date_visionnage, journal.id) AS jours_depuis_precedent
FROM journal
JOIN films ON films.id = journal.film_id
JOIN utilisateurs ON utilisateurs.id = journal.utilisateur_id
WHERE utilisateurs.pseudo = 'cinephile_92'
ORDER BY journal.date_visionnage, journal.id;